<?php $helper = $this->helper('Magepow\Gdpr\Helper\Data') ?>
<?php $active = $helper->getConfigModule('register/active') ?>
<?php if(!$active) return; ?>
<?php $label = $helper->getConfigModule('register/label') ?>
<div class="field choice magepow-gdpr-checkbox">
	<input name="accept_gdpr" value="1" id="accept_gdpr" class="checkbox" type="checkbox" data-validate="{required:true}"/>
	<label for="accept_gdpr" class="label"><span><?php echo $label ?></span></label>
</div>