<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-06-04 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-06-18 08:47:46
 */
?>
<form class="form form-gdpr-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate" data-mage-init='{"validation":{}}'>
	<fieldset class="fieldset">
		<?= $block->getBlockHtml('formkey') ?>
		<legend class="legend"><span><?php echo __('Data Access') ?></span></legend><br>
		<div class="field choice">
			<input name="remove_account" id="remove_account" value="1" title="<?php echo __('Erase Account') ?>" class="radio" type="radio" data-validate="{'validate-one-required-by-name':true}">
			<label for="remove_account" class="label"><span><?php echo __('Erase Account') ?></span></label>
		</div>
	</fieldset>
	<div class="actions-toolbar">
		<div class="primary"><button type="submit" title="<?php echo __('Sumit') ?>" class="action save primary"><span><?php echo __('Sumit') ?></span></button></div>
	</div>
</form>