<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-06-04 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-06-18 08:48:06
 */
?>
<?php 
    $helper 		= $this->helper('Magepow\Gdpr\Helper\Data');
    if( !$helper->getConfigModule('general/enabled') ) return;
?>
<?php $title        = $helper->getConfigModule('cookie_restriction/title'); ?>
<?php $content      = $helper->getConfigModule('cookie_restriction/content'); ?>
<?php $showMoreView = $helper->getConfigModule('cookie_restriction/more_view'); ?>
<?php $moreViewText = $helper->getConfigModule('cookie_restriction/more_text'); ?>
<?php $buttonText   = $helper->getConfigModule('cookie_restriction/button_text'); ?>
<?php $boxShadow    = $helper->getConfigModule('cookie_restriction/box_shadow'); ?>
<?php $width        = $helper->getConfigModule('cookie_restriction/width'); ?>
<?php $widthCustom  = $helper->getConfigModule('cookie_restriction/width_custom'); ?>
<?php $position     = $helper->getConfigModule('cookie_restriction/position'); ?>
<?php $marginLeft   = $helper->getConfigModule('cookie_restriction/margin_left'); ?>
<?php $marginRight  = $helper->getConfigModule('cookie_restriction/margin_right'); ?>
<?php $marginBottom = $helper->getConfigModule('cookie_restriction/margin_bottom'); ?>
<?php $fontSize     = $helper->getConfigModule('cookie_restriction/font_size'); ?>
<?php $textAlign    = $helper->getConfigModule('cookie_restriction/text_align'); ?>
<?php $identifier   = $helper->getConfigModule('cookie_restriction/identifier'); ?>
<?php $hiddenBottom = $helper->getConfigModule('cookie_restriction/hidden_bottom'); ?>
<?php $buttonClass  = $helper->getConfigModule('cookie_restriction/button_class'); ?>
<div role="alertdialog"
     tabindex="-1"
     data-hidden-bottom="<?php echo $hiddenBottom ?>"
     class="magepow-gdpr-cookie-notice message global cookie text-align-<?php echo $textAlign ?><?php if($boxShadow): ?> gdpr-box-shadow<?php endif ?>"
     id="notice-cookie-block"
     style="display: none;<?php if($width == 'custom' && $widthCustom!=''): ?>width:<?php echo $widthCustom ?>px;<?php endif ?><?php if($marginBottom!=''): ?>bottom:<?php echo $marginBottom ?>px;<?php endif ?><?php if($width == 'custom' && $position=='left' && $marginLeft!=''): ?>left:<?php echo $marginLeft ?>px; right:unset;<?php endif ?><?php if($width == 'custom' && $position=='right' && $marginLeft!=''): ?>right:<?php echo $marginRight ?>px; left:unset;<?php endif ?><?php if($fontSize!=''): ?>font-size:<?php echo $fontSize ?>px;<?php endif ?>">
    <span class="action-close cookie-close">
     	<span class="hidden">Close</span>
    </span>
    <div role="document" class="content" tabindex="0">
        <div class="info">
            <?php if($title!=''): ?>
				<div class="notice-cookie-title"><?php echo $title ?></div>
			<?php endif ?>
			<?php if($content!='' || ($showMoreView!='not-show' && $moreViewText!='')): ?>
				<div class="notice-cookie-content">
					<?php echo $content ?> 
					<?php if($showMoreView!='not-show' && $moreViewText!=''): ?>
						<a id="privacyLink" href="<?php echo $helper->getUrlBuilder($identifier) ?>"><?php echo $moreViewText ?></a>
					<?php endif ?>
				</div>
			<?php endif ?>
        </div>
        <div class="actions">
            <button id="btn-cookie-allow" class="btn-cookie allow primary <?php echo $buttonClass ? $buttonClass : ''; ?>">
                <span><?php echo $buttonText ?></span>
            </button>
        </div>
    </div>
</div>
<script type="text/javascript">
require(['jquery'], function($){
    $(window).on('scroll', function() {
        var $body = $('body');
        var $noticeCookie = $('#notice-cookie-block');
        var y = $(this).scrollTop();
        var isHidden = $noticeCookie.data('hidden-bottom') ? (y + $(this).height() == $(document).height()) : '';
        if (isHidden) $body.addClass('cookie-hidden-bottom');
        else $body.removeClass('cookie-hidden-bottom');
    });
});
</script>
<script type="text/x-magento-init">
    {
        "#notice-cookie-block": {
            "cookieNotices": {
                "cookieAllowButtonSelector": "#btn-cookie-allow",
                "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                "cookieValue": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getAcceptedSaveCookiesWebsiteIds() ?>,
                "cookieLifetime": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getCookieRestrictionLifetime() ?>,
                "noCookiesUrl": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('cookie/index/noCookies'))) ?>"
            }
        }
    }
</script>
<?php if($showMoreView=='popup' && $moreViewText!=''): ?>
	<div style="display:none" id="magepow-gdpr-popup-container">
		<div class="magepow-gdpr-popup" id="magepow-gdpr-popup" data-url="<?php /* @escapeNotVerified */ echo $this->getUrl('gdpr', array('_secure'=>$this->getRequest()->isSecure()))?>" >></div>
	</div>
	<?php if($showMoreView=='popup'): ?>
		<script type="text/javascript">require(['magepow/gdpr']);</script>
	<?php endif ?>
<?php endif ?>